export const RestaurantCategories = {
    FastFood: "FastFood",
    Pizza: "Pizza",
    Drinks: "Drinks",
    Family: "Family",
    Party: "Party",
    Romantic: "Romantic",
    Pub: "Pub",

    Italian: "Italian",
    American: "American",
    Asian: "Asian",
    Chinese: "Chinese",
    Japanese: "Japanese",
    Indian: "Indian",
    Mexican: "Mexican",
    Mediterranean: "Mediterranean",
    European: "European",
    Polish: "Polish",
    French: "French",
    Turkish: "Turkish",
    Thai: "Thai",
    Vegan: "Vegan",
    Vegetarian: "Vegetarian",
    Seafood: "Seafood",
    Steakhouse: "Steakhouse",
    BBQ: "BBQ",

    FineDining: "FineDining",
    CasualDining: "CasualDining",
    Cafe: "Cafe",
    Bakery: "Bakery",
    Buffet: "Buffet",
    StreetFood: "StreetFood",
    FoodCourt: "FoodCourt",

    Bar: "Bar",
    CocktailBar: "CocktailBar",
    WineBar: "WineBar",
    SportsBar: "SportsBar",
    LiveMusic: "LiveMusic",
    Rooftop: "Rooftop",
    Lounge: "Lounge",

    Business: "Business",
    DateNight: "DateNight",
    Birthday: "Birthday",
    Wedding: "Wedding",
    KidsFriendly: "KidsFriendly",
    PetFriendly: "PetFriendly",
    OutdoorDining: "OutdoorDining",

    Takeaway: "Takeaway",
    Delivery: "Delivery",
    AllYouCanEat: "AllYouCanEat",
    SelfService: "SelfService",
    DriveThru: "DriveThru",

    Fusion: "Fusion",
    LocalCuisine: "LocalCuisine",
    Healthy: "Healthy",
    Organic: "Organic",
    Breakfast: "Breakfast",
    Brunch: "Brunch",
    Dessert: "Dessert"
};